<?php

    namespace Cineflix\App\DAO;

    use Cineflix\App\DAO\List\StatusFilm;
    use Cineflix\App\Model\FilmModel;
    use Cineflix\Core\Database\Database;
    use Cineflix\Core\Util\MessageFlash;

    class FilmDao extends AbstractDAO
    {

        public function findOneBy(string $col, string $val, array $options = []): array
        {
            $result = parent::findOneBy($col, $val, $options);

            return $result;
        }

        public function findAll(array $params = []): array
        {
            $result = parent::findAll($params);

            foreach ($result as $key => $movie) {

                if(StatusFilm::EN_SALLE->value === $movie['status'] &&
                    $this->isExpired($movie['id'])) {

                    $data = ['id' => $movie['id'],
                             'status' => StatusFilm::INDISPONIBLE->value];
                    $this->update($data);

                    if(isset($params['params']['status']) && $params['params']['status'] === StatusFilm::EN_SALLE->value) {
                        unset($result[$key]);
                    }
                }
            }
            return $result;
        }

        /**
         * @param FilmModel $movie
         *
         * @return void
         */
        public function create(object $movie)
        {

            try {

                $this->db->beginTransaction();

                $movie_data = [
                    'nom'           => $movie->nom,
                    'synopsis'      => $movie->synopsis,
                    'date_sortie'   => $movie->date_sortie,
                    'status'        => $movie->status_id,
                    'slug'          => $movie->getSlug(),
                ];

                if($movie->status === StatusFilm::EN_SALLE){

                    if(is_null($movie->cinema->ville->id)) {

                        $ville_data = [
                            'nom' => $movie->cinema->ville->nom
                        ];
                        $this->db->insert('ville', $ville_data);
                        $movie->cinema->ville->setId($this->db->getLastInsertId());
                    }

                    if(is_null($movie->cinema->id)) {
                        $cinema_data = [
                            'nom' => $movie->cinema->nom,
                            'ville_id' => $movie->cinema->ville->id
                        ];

                        $this->db->insert('cinema', $cinema_data);
                        $movie->cinema->setId($this->db->getLastInsertId());

                    }

                    $movie_data['cinema_id'] = $movie->cinema->id;
                }


                $this->db->insert($this->table,$movie_data);
                $this->last_id = $this->db->getLastInsertId();


                if($movie->status === StatusFilm::EN_SALLE) {
                    $exploitation = [
                        'film_id' => $this->last_id,
                        'debut'   => $movie->exploitation->debut,
                        'fin'     => $movie->exploitation->fin,
                    ];
                    $this->db->insert('exploitation' ,$exploitation);
                }


                $this->db->commit();

                $result = true;

            } catch (\PDOException $e) {
                $result = false;

                $this->db->rollback();

                MessageFlash::create("PDOException: " . $e->getMessage(),'erreur');
            }


            return $result;

        }

        public function update($data, string $id_column = 'id'): Database
        {
            return parent::update($data, $id_column); // TODO: Change the autogenerated stub
        }

        private function isExpired($id): bool
        {
            $sql = 'SELECT EXISTS ( 
                                SELECT 1
                                FROM exploitation e
                                WHERE e.fin = (
                                    SELECT MAX(fin)
                                    FROM exploitation
                                    WHERE film_id = :film_id
                                ) AND e.fin < CURRENT_DATE
                            ) AS result';

            $req = $this->db->createCustomQuery($sql)
                ->setParameter('film_id', $id);

            $expire = $req->fetch();

            return $expire['result'];
        }
    }